project_id = "tkrlqndprgmgpebjirot"

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-satispay-payment]
verify_jwt = false

[functions.check-satispay-payment]
verify_jwt = false

[functions.create-paypal-order]
verify_jwt = false

[functions.capture-paypal-order]
verify_jwt = false

[functions.export-registrations]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.explore-firestore]
verify_jwt = false

[functions.import-firestore]
verify_jwt = false

[functions.merge-participants]
verify_jwt = false

[functions.update-participant]
verify_jwt = false
