project_id = "tkrlqndprgmgpebjirot"

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-satispay-payment]
verify_jwt = false

[functions.check-satispay-payment]
verify_jwt = false
